schemaVersion: 2.0.0
commandTests:
  - name: "Triton Server"
    command: "which"
    args: ["tritonserver"]
    expectedOutput: ["/opt/tritonserver/bin/tritonserver"]
  - name: "Merlin Core tests"
    command: "pytest"
    args: ["/core/tests/unit/"]
    exitCode: 0
  - name: "NVTabular tests"
    command: "pytest"
    args: ["/nvtabular/tests/unit/"]
    exitCode: 0
