schemaVersion: 2.0.0
commandTests:
  - name: "Torch Python package"
    command: "python"
    args: ["-c", "import torch"]
    expectedOutput: [""]
  - name: "Merlin Core tests"
    command: "pytest"
    args: ["/core/tests/unit/"]
    exitCode: 0
  - name: "NVTabular tests"
    command: "pytest"
    args: ["/nvtabular/tests/unit/"]
    exitCode: 0
  - name: "Transformers4Rec tests"
    command: "pytest"
    args: ["/transformers4rec/tests/torch/"]
    exitCode: 0
