schemaVersion: 2.0.0
commandTests:
  - name: "CuPy Python package"
    command: "python"
    args: ["-c", "import cupy"]
    expectedOutput: [""]
  - name: "CuDF Python package"
    command: "python"
    args: ["-c", "import cudf"]
    expectedOutput: [""]
  - name: "HugeCTR Python package"
    command: "python"
    args: ["-c", "import hugectr"]
    expectedOutput: [""]
  - name: "Merlin Core tests"
    command: "pytest"
    args: ["/core/tests/unit/"]
    exitCode: 0
  - name: "NVT notebook tests"
    command: "pytest"
    args: ["/nvtabular/tests/unit/test_notebooks.py"]
    exitCode: 0
