schemaVersion: 2.0.0
commandTests:
  - name: "Triton Server"
    command: "which"
    args: ["tritonserver"]
    expectedOutput: ["/opt/tritonserver/bin/tritonserver"]
  - name: "CuPy Python package"
    command: "python"
    args: ["-c", "import cupy"]
    expectedOutput: [""]
  - name: "CuDF Python package"
    command: "python"
    args: ["-c", "import cudf"]
    expectedOutput: [""]
  - name: "Merlin Core tests"
    command: "pytest"
    args: ["/core/tests/unit/"]
    exitCode: 0
  - name: "NVTabular tests"
    command: "pytest"
    args: ["/nvtabular/tests/unit/"]
    exitCode: 0
